routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/admin')->group(function(){
	Route::get('/', 'AdminController@index')->name('admin.dashboard');
	Route::get('/login', 'Auth\Admin\AdminLoginController@showLoginForm')->name('admin.login');
	Route::post('/login/submit', 'Auth\Admin\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/logout', 'Auth\Admin\AdminLoginController@adminLogout')->name('admin.logout');

    Route::get('/profile/{admin}', 'AdminController@adminProfile')->name('admin.profile');
    Route::post('/profile/{admin}', 'AdminController@changePassword')->name('admin.change.password');

    // For Admin Password Reset
    Route::post('/password/email', 'Auth\Admin\AdminForgotPasswordController@sendResetLinkEmail' )->name('admin.password.email');
	Route::get('/password/reset', 'Auth\Admin\AdminForgotPasswordController@showLinkRequestForm' )->name('admin.password.update');
	Route::post('/password/reset', 'Auth\Admin\AdminResetPasswordController@reset' );
	Route::get('/password/reset/{token}', 'Auth\Admin\AdminResetPasswordController@showResetForm' )->name('admin.password.reset');


	//User CRUD on admin

	Route::prefix('/users')->group(function(){
		Route::get('/list', 'Admin\UsersController@index')->name('admin.users.list');
		Route::get('/add', 'Admin\UsersController@show')->name('admin.users.add');
		Route::post('/submit', 'Admin\UsersController@store')->name('admin.user.submit');
		Route::get('/edit/{id}', 'Admin\UsersController@edit')->name('admin.users.edit');
		Route::post('/update/{id}', 'Admin\UsersController@update')->name('admin.users.update');
		Route::get('/delete/{id}', 'Admin\UsersController@destroy')->name('admin.users.delete');
	});

	// Property Crud

	Route::prefix('/property')->group(function(){
		Route::get('/list', 'Admin\PropertyController@index')->name('admin.property.list');
		Route::get('/add', 'Admin\PropertyController@show')->name('admin.property.add');
		Route::post('/submit', 'Admin\PropertyController@store')->name('admin.property.submit');
		Route::get('/edit/{id}', 'Admin\PropertyController@edit')->name('admin.property.edit');
		Route::post('/update/{id}', 'Admin\PropertyController@update')->name('admin.property.update');
		Route::get('/delete/{id}', 'Admin\PropertyController@destroy')->name('admin.property.delete');
	});

	// Category Crud

	Route::prefix('/category')->group(function(){
		Route::get('/list', 'Admin\QuesCategoryController@index')->name('admin.category.list');
		Route::get('/add', 'Admin\QuesCategoryController@show')->name('admin.category.add');
		Route::post('/submit', 'Admin\QuesCategoryController@store')->name('admin.category.submit');
		Route::get('/edit/{id}', 'Admin\QuesCategoryController@edit')->name('admin.category.edit');
		Route::post('/update/{id}', 'Admin\QuesCategoryController@update')->name('admin.category.update');
		Route::get('/delete/{id}', 'Admin\QuesCategoryController@destroy')->name('admin.category.delete');
	});

	// Question Crud

	Route::prefix('/question')->group(function(){
		Route::get('/list', 'Admin\QuestionController@index')->name('admin.question.list');
		Route::get('/add', 'Admin\QuestionController@show')->name('admin.question.add');
		Route::post('/submit', 'Admin\QuestionController@store')->name('admin.question.submit');
		Route::get('/edit/{id}', 'Admin\QuestionController@edit')->name('admin.question.edit');
		Route::post('/update/{id}', 'Admin\QuestionController@update')->name('admin.question.update');
		Route::get('/delete/{id}', 'Admin\QuestionController@destroy')->name('admin.question.delete');
	});

	// Terms CRUD

	Route::resource('term', 'Admin\TermController');

});

// Frontend Routes

Route::redirect('/', app()->getLocale() . '/login');

Route::group(["prefix" => "{language}"], function(){
	Route::get('/', 'HomeController@home')->name('home');
	Route::get('/properties/{term}', 'HomeController@index')->name('property.term');
	Route::get('/property/{id}', 'HomeController@propertyQuestions')->name('property');
	Route::get('/property/{id}/question', 'HomeController@questions')->name('question');
	Route::post('/answers/submit/{property}', 'HomeController@answers')->name('answers.submit');
	Route::post('/property/{property}/question/{question}', 'HomeController@deleteImage');	
});

Route::group(["prefix" => "{language?}"], function(){
	Auth::routes(['register' => false]);
});

app/Property.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;
use Carbon\Carbon;

class Property extends Model
{
    protected $fillable = [
    	'property_name', 'property_slug', 'property_status'
    ];

    public function getPropertyDesc(){
    	return $this->hasOne('App\PropertyDesc', 'property_id');
    }

    public function questions(){
	    return $this->belongsToMany('App\Question', 'property_question', 'property_id', 'question_id');
	}

	public static function groupByQues($id, $term_id){
		$allQues =  DB::table('property_question')
	                ->where('property_question.property_id', '=', $id )
	                ->join('questions', 'property_question.question_id', '=', 'questions.id')
	                ->join('ques_categories', 'questions.category_id', '=', 'ques_categories.id' )
	                ->join('question_term', 'question_term.question_id', '=', 'questions.id')
	                ->where('question_term.term_id', $term_id)
	                ->select('ques_categories.*', 'questions.*')
	                ->where('ques_categories.cat_status', '=', 'a')
	                ->get();
	    
	    return $allQues;
	}

	public function answers(){
	    return $this->hasMany('App\Answer');
	}

	public static function groupByAnswer($id, $term_id){
		$answer =  DB::table('property_question')
	                ->where('property_question.property_id', '=', $id )
	                ->join('questions', 'property_question.question_id', '=', 'questions.id')
	                ->join('ques_categories', 'questions.category_id', '=', 'ques_categories.id' )
	                ->join('question_term', 'question_term.question_id', '=', 'questions.id')
	                ->join('answers', 'answers.question_id', '=', 'questions.id')
	                ->where('answers.property_id', $id)
	                ->where('answers.term_id', $term_id)
	                ->where('question_term.term_id', $term_id)
	                ->select('ques_categories.*', 'questions.*', 'answers.*')
	                ->where('ques_categories.cat_status', '=', 'a')
	                ->get();
	    
	    return $answer;
	}

	public function getUpdatedAtAttribute($date){
	    return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d-m-Y');
	}

	public function getScore($term){
		$questions = self::groupByQues($this->id, $term)->count();
		$answers   = self::groupByAnswer($this->id, $term);

		$groupByAnswer = $answers->groupBy('answer');

		$positive1 = $this->checkIfEmpty($groupByAnswer, 'Yes' );
        $positive2 = $this->checkIfEmpty($groupByAnswer, 'N/A' );
        $negative  = $this->checkIfEmpty($groupByAnswer, 'No' );

        $allPositive = $positive1 + $positive2;

        if($questions){
            $score  = round((100/$questions) * $allPositive);
        } else {
            $score = 0;
        }
        return $score;

	}

	private function checkIfEmpty($answer, $value){
        if(!empty($answer) && isset($answer[$value])){
            $newValue = $answer[$value]->count();
        } else{
            $newValue = 0;
        }
        return $newValue;
    }
}

resources/views/index.blade.php
@extends('layouts.app')

@section('language')

<div class="language-switcher-wrapper">
    <a href="{{route(Route::currentRouteName(), 'en')}}"><img src="{{asset('assets/images/en.png')}}" class="fr"></a>
    <a href="{{route(Route::currentRouteName(), 'nl')}}"><img src="{{asset('assets/images/nl.png')}}" class="en"></a>
</div>

@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">

        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif

    </div>
</div>

<section class="section section-default mt-none mb-none section-services">
    <div class="container">
        <h2 class="mb-sm"><strong>{{__('select terms')}}</strong></h2>
        <div class="row">
            @if(!empty($terms))
            @foreach($terms as $term)
            <div class="col-xs-12 col-sm-4 col-lg-2">
                <a href="{{route('property.term',['language' => app()->getLocale(),'term'=>$term->id] )}}">
                
                    <div class="service-block-container">
                        <div class="service-block">
                            <div class="service-underlay">
                                <span class="service-name">{{$term->term_name}}</span>
                            </div>
                            <!-- <span class="service-icon">
                                <em class="fa fa-code"></em>
                            </span> -->
                            
                        </div>
                    </div>
                </a>
            </div>
            @endforeach
            @endif
        </div>
    </div>
</section>


@endsection

resources/views/properties.blade.php
@extends('layouts.app')

@section('language')

<div class="language-switcher-wrapper">
    <a href="{{route(Route::currentRouteName(), ['language' => 'en', 'term' => $term])}}"><img src="{{asset('assets/images/en.png')}}" class="fr"></a>
    <a href="{{route(Route::currentRouteName(), ['language' => 'nl', 'term' => $term])}}"><img src="{{asset('assets/images/nl.png')}}" class="en"></a>
</div>

@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">

        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif

    </div>
</div>

<div class="bs-example" data-example-id="striped-table" style="padding:20px;">

    <div class="property-info-wrapper" style="padding-bottom:30px;">
        <h3>{{__('properties')}}</h3>
        
    </div>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th style="width:15%; text-align: center;">Logo</th>
                <th style="width:50%%; text-align: center;">{{__('name')}}</th>
                <th style="width:5%; text-align: center;">{{__('score')}}</th>
                <th style="text-align: center;">{{__('action')}}</th>
            </tr>
        </thead>
        <tbody>

        	@foreach($properties as $property)
            
            <tr class="property-table" style="cursor:pointer;" data-href="/{{app()->getLocale()}}/property/{{$property->id}}">
                
                <td class="property-tbl-td"><a href="{{route('property', ['language' => app()->getLocale(),'id'=>$property->id])}}">
                	@php
                	if(!empty($property->getPropertyDesc->logo)){
                        $image = asset('admin_assets/assets/image/' . $property->getPropertyDesc->logo);
                	} else {
                		$image = '';
                	}
                	@endphp
                	@if(!empty($image))
                	<img src="{{$image}}" style="height:100px;" />
                	@endif
                </a></td>
                <td class="property-tbl-td"> 
                    {{$property->property_name}}
                </td>
                <td class="property-tbl-td">
                    {{$property->getScore($term)}}%
                </td>
                <td class="property-tbl-td">
                    <button style="background: #67d5bf; color: #fff;border:none;">{{__('details')}}</button>
                </td>
               
            </tr>

            @endforeach

        </tbody>
    </table>
</div>


<div class="tbl-mobile-accordion-wrapper" style="margin:20px; display: none;">

    <div class="table mobile-accordion">
        <div class="thead">
            <div class="tr">

                <th class="th">{{__('logo')}}</th>
                <th class="th">{{__('name')}}</th>
                <th class="th">{{__('score')}}</th>
                <th class="th">{{__('action')}}</th>

            </div>
        </div>
        <div class="tbody">

            @foreach ($properties as $property)

            <div class="rh"><span>{{$property->property_name}}</span></div>
            <div class="tr">
                <div class="td" data-header="{{__('logo')}}:">
                	@php
                	if(!empty($property->getPropertyDesc->logo)){
                        $image = asset('admin_assets/assets/image/' . $property->getPropertyDesc->logo);
                	} else {
                		$image = '';
                	}
                	@endphp
                	@if(!empty($image))
                	<img src="{{$image}}" style="height:100px;" />
                	@endif
                </div>
                <div class="td" data-header="{{__('name')}}:">{{$property->property_name}}</div>
                <div class="td" data-header="{{__('score')}}:">{{$property->getScore($term)}}%</div>
                <div style="margin:20px; text-align: center;">
                	<a href="{{route('property', ['language' => app()->getLocale(),'id'=>$property->id])}}">
	                	<button style="background: #67d5bf; color: #fff;border:none;">{{__('details')}}</button>
	                </a>
                </div>
            </div>

            @endforeach

        </div>
    </div>
</div>


@endsection

resources/views/property.blade.php
@extends('layouts.app')

@section('language')

<div class="language-switcher-wrapper">
    <a href="{{route(Route::currentRouteName(), ['language' => 'en', 'id' => $property->id])}}"><img src="{{asset('assets/images/en.png')}}" class="fr"></a>
    <a href="{{route(Route::currentRouteName(), ['language' => 'nl', 'id' => $property->id])}}"><img src="{{asset('assets/images/nl.png')}}" class="en"></a>
</div>

@endsection

@section('content')

<div class="bs-example" data-example-id="striped-table" style="padding:20px;">

    <div class="property-info-wrapper" style="padding-bottom:30px;">
        <h3>{{__('property information')}}</h3>
        <p><span> {{__('hotel name')}} : </span> <strong>{{$property->property_name}}</strong></p>
        <p><span> {{__("year")}} : </span> <strong>{{date("Y")}}</strong></p>
        <p><span> Score : </span> <strong>{{$score}}%</strong></p>
        <p><span> {{__('last update')}} : </span> <strong>{{$property->updated_at}}</strong></p>
        <!-- <p><span> Username : </span> <strong>Pritom</strong></p> -->
    </div>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>{{__('question')}}</th>
                <th>{{__('answer')}}</th>
                <th>{{__('remarks')}}</th>
                <th>{{__('deadline')}}</th>
                <th>{{__('reminder')}}</th>
                <th>{{__('evidence')}}</th>
            </tr>
        </thead>
        <tbody>
        	@if(!empty($groupQuestions))
     		@php 
     		$count = 1;
            $alphabet = 0;
     		$serial = range('A', 'Z');
     		@endphp
        	@foreach ( $groupQuestions as $key => $questions )
        	
        	<tr>
        		<td colspan="7" style="background: #e9f0fa;">{{$serial[$alphabet]}}. {{ $key }}</td>
        	</tr>
        	
        	@if(!empty( $questions ))
        	@foreach ($questions as $singleQuestion)
            @php 
            $answers = abc($singleQuestion->id, $property->id, $term);
            
            @endphp
            
            <tr class="property-table" style="cursor:pointer;" data-href="/{{app()->getLocale()}}/property/{{$property->id}}/question/?question={{$singleQuestion->id}}">
                
                <td><strong>{{$count}}</strong></td>
                <td><a href="{{route('question', ['language' => app()->getLocale(),'id'=>$property->id, 'question'=>$singleQuestion->id])}}">{{$singleQuestion->ques_name}}</a></td>
                <td> 
                    @php
                    if(!empty($answers) && isset($answers->answer)){
                        if($answers->answer == "Yes"){
                            echo __('yes');
                        }

                        if($answers->answer == "No"){
                            echo __('no');
                        }

                        if($answers->answer == "N/A"){
                            echo __('n/a');
                        } 
                    }
                    @endphp
                </td>
                <td>
                    @php
                    if(!empty($answers) && isset($answers->remarks)){
                        echo $answers->remarks;
                    }
                    @endphp
                </td>
                <td>
                    @php
                    if(!empty($answers) && isset($answers->deadline)){
                        echo $answers->deadline;
                    }
                    @endphp
                </td>
                <td>
                    @php
                    if(!empty($answers) && isset($answers->reminder)){
                        echo $answers->reminder;
                    }
                    @endphp
                </td>
                <td>
                    @if(!empty($answers) && $answers->images->count() > 0)
                    Yes
                    @else
                    No
                    @endif
                </td>
               
            </tr>
            
            @php $count++ @endphp

            @endforeach
            @endif
            @php $alphabet++ @endphp
            @endforeach
            @else
            <h1>There are no questions of this property</h1>
            @endif

        </tbody>
    </table>
</div>

<div class="tbl-mobile-accordion-wrapper" style="margin:20px; margin-bottom: 60px; display: none;">

    <div class="table mobile-accordion">
        <div class="thead">
            <div class="tr">
                <div class="th">{{__('question')}}</div>
                <div class="th">{{__('answer')}}</div>
                <div class="th">{{__('remarks')}}</div>
                <!-- <div class="th">Priority</div> -->
                <div class="th">{{__('deadline')}}</div>
                <div class="th">{{__('reminder')}}</div>
                <div class="th">{{__('evidence')}}</div>
                <th class="th">{{__('action')}}</th>
            </div>
        </div>
        <div class="tbody">

            @if(!empty($groupQuestions))
            @php 
            $count = 1;
            $alphabet = 0;
            $serial = range('A', 'Z');
            @endphp

            @foreach ( $groupQuestions as $key => $questions )
            
            @if(!empty( $questions ))
            @foreach ($questions as $singleQuestion)

            @php 
            $answers = abc($singleQuestion->id, $property->id, $term);
            
            @endphp

            <div class="rh"><span>{{$singleQuestion->ques_name}}</span></div>
            <div class="tr">
                <div class="td" data-header="{{__('question')}}:">{{$singleQuestion->ques_name}}</div>
                <div class="td" data-header="{{__('answer')}}:">
                     
                    @php
                    if(!empty($answers) && isset($answers->answer)){
                        if(!empty($answers) && isset($answers->answer)){
                            if($answers->answer == "Yes"){
                                echo __('yes');
                            }

                            if($answers->answer == "No"){
                                echo __('no');
                            }

                            if($answers->answer == "N/A"){
                                echo __('n/a');
                            } 
                        }
                    }
                    @endphp
               
                </div>
                <div class="td" data-header="{{__('remarks')}}:">
                    @php
                    if(!empty($answers) && isset($answers->remarks)){
                        echo $answers->remarks;
                    }
                    @endphp
                </div>
                <div class="td" data-header="{{__('deadline')}}:">
                    @php
                    if(!empty($answers) && isset($answers->deadline)){
                        echo $answers->deadline;
                    }
                    @endphp
                </div>
                <div class="td" data-header="{{__('reminder')}}:">
                    @php
                    if(!empty($answers) && isset($answers->reminder)){
                        echo " &nbsp ". $answers->reminder;
                    }
                    @endphp
                </div>
                <div class="td" data-header="{{__('evidence')}}:">
                    @if(!empty($answers) && $answers->images->count() > 0)
                    Yes
                    @else
                    No
                    @endif
                </div>
                <div style="margin:20px; text-align: center;">
                    <a href="{{route('question', ['language' => app()->getLocale(),'id'=>$property->id, 'question'=>$singleQuestion->id])}}"><button style="background: #67d5bf; color: #fff;border:none;">{{__('details')}}</button></a>
                </div>
            </div>

            @php $count++; @endphp
            @endforeach
            @endif
            @php $alphabet++ @endphp
            @endforeach
            @else
            <h1>There are no questions of this property</h1>
            @endif

        </div>
    </div>
</div>

@endsection

resources/views/questions.blade.php
@extends('layouts.app')

@section('language')

<div class="language-switcher-wrapper">

    <a href="{{route(Route::currentRouteName(), ['language' => 'en', 'id' => $property->id, 'question' => $value])}}"><img src="{{asset('assets/images/en.png')}}" class="fr"></a>
    <a href="{{route(Route::currentRouteName(), ['language' => 'nl', 'id' => $property->id, 'question' => $value])}}"><img src="{{asset('assets/images/nl.png')}}" class="en"></a>

</div>

@endsection

@section('content')
<div class="container">

    <div class="row justify-content-center">

        <div class="col-md-8">

            <div class="back-btn-wrapper">
                <a href="{{route('property', ['language' => app()->getLocale(),'id'=>$property->id])}}">
                    <button class="button" style="background: #67d5bf; color: #fff; border:none;">Go Back</button>
                </a>
            </div>

            <form id="msform" action="{{route('answers.submit',['language'=> app()->getLocale(), 'property' => $property->id])}}" method="post" enctype="multipart/form-data">
                @csrf
                <ul id="progressbar">
                    @php $count = 1 @endphp
                    @foreach($questions as $question)
                        @php
                        if($question->id == $value){
                            $abc = "class=active";                              
                        } else {
                            $abc = '';
                        }
                        @endphp

                        <li {{$abc}}></li>
                        
                        @php $count++ @endphp

                    @endforeach

                </ul>

                @if (session('status'))
                    <div class="alert alert-success" role="alert" style="text-align:center;">
                        {{ session('status') }}
                    </div>
                @endif

                <div class="question-wrapper" property_id="{{$property->id}}">

                    @php 
                    $i = 1;
                    $propertyId = $property->id;
                    $total = count($questions)
                    @endphp
                    
                    @foreach($questions as $key => $question)
                        @php
                        if( $key != count( $questions ) - 1 ){
                            $last = false;
                        } else {
                            $last = true;
                        }

                        @endphp
                        <x-questioncomponent :index="$i" :question="$question" :last="$last" :total="$total"  :propertyId="$propertyId" />
                        @php $i++ @endphp
                    @endforeach

                </div>

            </form>

        </div>
    </div>
</div>

@endsection