routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/admin')->group(function(){
	Route::get('/', 'AdminController@index')->name('admin.dashboard');
	Route::get('/login', 'Auth\Admin\AdminLoginController@showLoginForm')->name('admin.login');
	Route::post('/login/submit', 'Auth\Admin\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/logout', 'Auth\Admin\AdminLoginController@adminLogout')->name('admin.logout');

    Route::get('/profile/{admin}', 'AdminController@adminProfile')->name('admin.profile');
    Route::post('/profile/{admin}', 'AdminController@changePassword')->name('admin.change.password');

    // For Admin Password Reset
    Route::post('/password/email', 'Auth\Admin\AdminForgotPasswordController@sendResetLinkEmail' )->name('admin.password.email');
	Route::get('/password/reset', 'Auth\Admin\AdminForgotPasswordController@showLinkRequestForm' )->name('admin.password.update');
	Route::post('/password/reset', 'Auth\Admin\AdminResetPasswordController@reset' );
	Route::get('/password/reset/{token}', 'Auth\Admin\AdminResetPasswordController@showResetForm' )->name('admin.password.reset');


	//User CRUD on admin

	Route::prefix('/users')->group(function(){
		Route::get('/list', 'Admin\UsersController@index')->name('admin.users.list');
		Route::get('/add', 'Admin\UsersController@show')->name('admin.users.add');
		Route::post('/submit', 'Admin\UsersController@store')->name('admin.user.submit');
		Route::get('/edit/{id}', 'Admin\UsersController@edit')->name('admin.users.edit');
		Route::post('/update/{id}', 'Admin\UsersController@update')->name('admin.users.update');
		Route::get('/delete/{id}', 'Admin\UsersController@destroy')->name('admin.users.delete');
	});

	// Property Crud

	Route::prefix('/property')->group(function(){
		Route::get('/list', 'Admin\PropertyController@index')->name('admin.property.list');
		Route::get('/add', 'Admin\PropertyController@show')->name('admin.property.add');
		Route::post('/submit', 'Admin\PropertyController@store')->name('admin.property.submit');
		Route::get('/edit/{id}', 'Admin\PropertyController@edit')->name('admin.property.edit');
		Route::post('/update/{id}', 'Admin\PropertyController@update')->name('admin.property.update');
		Route::get('/delete/{id}', 'Admin\PropertyController@destroy')->name('admin.property.delete');
	});

	// Category Crud

	Route::prefix('/category')->group(function(){
		Route::get('/list', 'Admin\QuesCategoryController@index')->name('admin.category.list');
		Route::get('/add', 'Admin\QuesCategoryController@show')->name('admin.category.add');
		Route::post('/submit', 'Admin\QuesCategoryController@store')->name('admin.category.submit');
		Route::get('/edit/{id}', 'Admin\QuesCategoryController@edit')->name('admin.category.edit');
		Route::post('/update/{id}', 'Admin\QuesCategoryController@update')->name('admin.category.update');
		Route::get('/delete/{id}', 'Admin\QuesCategoryController@destroy')->name('admin.category.delete');
	});

	// Question Crud

	Route::prefix('/question')->group(function(){
		Route::get('/list', 'Admin\QuestionController@index')->name('admin.question.list');
		Route::get('/add', 'Admin\QuestionController@show')->name('admin.question.add');
		Route::post('/submit', 'Admin\QuestionController@store')->name('admin.question.submit');
		Route::get('/edit/{id}', 'Admin\QuestionController@edit')->name('admin.question.edit');
		Route::post('/update/{id}', 'Admin\QuestionController@update')->name('admin.question.update');
		Route::get('/delete/{id}', 'Admin\QuestionController@destroy')->name('admin.question.delete');
	});

	// Terms CRUD

	Route::resource('term', 'Admin\TermController');

});

// Frontend Routes

Route::redirect('/', app()->getLocale() . '/login');

Route::group(["prefix" => "{language}"], function(){
	Route::get('/', 'HomeController@home')->name('home');
	Route::get('/properties/{term}', 'HomeController@index')->name('property.term');
	Route::get('/property/{id}', 'HomeController@propertyQuestions')->name('property');
	Route::get('/property/{id}/question', 'HomeController@questions')->name('question');
	Route::post('/answers/submit/{property}', 'HomeController@answers')->name('answers.submit');
	Route::post('/property/{property}/question/{question}', 'HomeController@deleteImage');	
});

Route::group(["prefix" => "{language?}"], function(){
	Auth::routes(['register' => false]);
});

app/Term.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Term extends Model
{
    protected $fillable = ['term_name', 'term_status'];

    public function questions(){
    	return $this->belongsToMany('App\Question');
    }

    public function answers(){
    	return $this->hasMany('App\Answer');
    }
}

app/Http/Controllers/Admin/TermController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\TermRequest;
use App\Term;

class TermController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $terms = Term::paginate(10);
        return view('admin.term.list-term', compact('terms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.term.add-term');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TermRequest $request)
    {
        Term::create($request->all());
        return redirect(route('term.index'))->with('message', 'Term successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Term $term)
    {
        return view('admin.term.edit-term', compact('term'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TermRequest $request, Term $term)
    {
        $term->update($request->all());
        return redirect(route('term.edit', $term->id))->with('message', 'Term successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Term $term)
    {
        $term->delete();
        return redirect(route('term.index'))->with('message', 'Term deleted updated');
    }
}

resources/views/admin/term/add-term.blade.php
@extends('admin.partials.layout')
@section('title', 'Add Term')
@section('term', 'active')
@extends('admin.partials.header')
@extends('admin.partials.sidebar')


@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title list-heading-wrapper-left">Add Term</h3>
                    <div class="list-heading-wrapper-right">
                    	<a href="{{route('term.index')}}" class="btn btn-primary heading-wrapper-button">View All</a>
                    </div>
                </div>
                <div class="panel-body rad-map-container">

                	@if ($errors->any())
					    <div class="alert alert-danger">
					        <ul>
					            @foreach ($errors->all() as $error)
					                <li>{{ $error }}</li>
					            @endforeach
					        </ul>
					    </div>
					@endif

                	<form action="{{route('term.store')}}" method="post">

                		@csrf
                		<div class="col-md-6">
						  	<div class="form-group">
						    	<label for="Username">Term Name</label>
						    	<input type="text" name="term_name" class="form-control" placeholder="Enter Term Name" id="username" required />
						  	</div>
						</div>

						<div class="col-md-12">
					  		<button type="submit" class="btn btn-primary pull-right">Submit</button>
					  	</div>

					</form>

                </div>         
               
            </div>
        </div>
    </div>

    



@endsection

resources/views/admin/term/edit-term.blade.php
@extends('admin.partials.layout')
@section('title', 'Edit Term')
@section('term', 'active')
@extends('admin.partials.header')
@extends('admin.partials.sidebar')

@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title list-heading-wrapper-left">Edit Term</h3>
                    <div class="list-heading-wrapper-right">
                    	<a href="{{route('term.index')}}" class="btn btn-primary heading-wrapper-button">View All</a>
                    </div>
                </div>
                <div class="panel-body rad-map-container">

                	@if ($errors->any())
					    <div class="alert alert-danger">
					        <ul>
					            @foreach ($errors->all() as $error)
					                <li>{{ $error }}</li>
					            @endforeach
					        </ul>
					    </div>
					@endif

					@if(Session::has('message'))
                        <p class="alert alert-info">{{ Session::get('message') }}</p>
                    @endif

                	<form action="{{route('term.update', $term->id)}}" method="post">
                		@method('PUT')
                		@csrf
                		<div class="col-md-6">
						  	<div class="form-group">
						    	<label for="Username">Term Name</label>
						    	<input type="text" name="term_name" class="form-control" placeholder="Enter Term Name" id="username" value="{{$term->term_name}}" required />
						  	</div>
						</div>

						<div class="col-md-12">
					  		<button type="submit" class="btn btn-primary pull-right">Submit</button>
					  	</div>

					</form>

                </div>         
               
            </div>
        </div>
    </div>

    



@endsection

resources/views/admin/term/list-term.blade.php
@extends('admin.partials.layout')
@section('title', 'List Term')
@extends('admin.partials.header')
@section('Term', 'active')
@extends('admin.partials.sidebar')


@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title list-heading-wrapper-left">Term List</h3>
                    <div class="list-heading-wrapper-right">
                    	<a href="{{route('term.create')}}" class="btn btn-primary heading-wrapper-button">Add New</a>
                    </div>
                </div>
                <div class="panel-body rad-map-container">

                	@if(Session::has('message'))
                        <p class="alert alert-info">{{ Session::get('message') }}</p>
                    @endif

                	<div class="tbl-header">
				        <table cellpadding="0" cellspacing="0" border="0">
				            <thead>
				                <tr>
				                    <th>SL</th>
				                    <th>Term Name</th>
				                    <th>Action</th>
				                </tr>
				            </thead>
				        </table>
				    </div>
				    <div class="tbl-content">
				        <table cellpadding="0" cellspacing="0" border="0">
				            <tbody>
				            	@php $count = 0 @endphp
				            	@foreach ($terms as $term)

				            		<tr>
					                    <td>{{ $count + $terms->firstItem() }}</td>
					                    <td>{{$term->term_name}}</td>
					                    

					                    <td>
					                    	<a href="{{route('term.edit', $term->id)}}"><button>Edit</button></a>

					                    	<form method="post" action="{{route('term.destroy', $term->id)}}" style="display: inline-block;vertical-align: top; margin-left:10px;">
					                    		@method('DELETE')
					                    		@csrf
					                    		<button type="submit" onclick="return confirm('Are you sure you want to delete this item?');">Delete</button>
					                    	</form>
					                    </td>
					                </tr>

						        <?php $count++; ?>
						    	@endforeach

				            </tbody>
				        </table>
				    </div>

                </div>
              
              	<div class="click-option" style="margin:20px;">
                	{{$terms->links()}}
                </div>  
               
            </div>
        </div>
    </div>

    



@endsection